name: micros

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Micros
        run: |
          go build ./...
          go test ./...